# Getting started with pandas - Intro

This chapter introduces you to the pandas package. It also serves as a test for your technical setup.

# Load required packages and setup display of dataframes

In [1]:
import pandas as pd

pd.set_option("display.max_columns", 500)

# Loading data from a CSV file and inspecting it

In [2]:
df = pd.read_csv("../../data/raw/financial_data_intro.csv")
df.head()

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False
3,14651,2008,British American Tobacco PLC,312230,GBR,2008-12-31,110448107,40276.807,3591.888,False
4,14651,2009,British American Tobacco PLC,312230,GBR,2009-12-31,110448107,43026.854,4386.107,False

In [3]:
df.describe()

,u_company_name_id,u_year,cb_naics,cb_at,cb_ni
count,824.000000,824.000000,824.000000,8.240000e+02,824.000000
mean,45233.387136,2012.111650,379140.905340,1.136859e+05,2191.241188
std,32869.292595,4.166015,207892.935774,2.963489e+05,5047.784304
min,2172.000000,2005.000000,325.000000,0.000000e+00,-50119.000000
25%,14651.000000,2009.000000,324110.000000,7.634920e+02,-0.312750
50%,34617.000000,2012.000000,336111.000000,1.647187e+04,484.862000
75%,77954.000000,2016.000000,523930.000000,8.486373e+04,3470.270750
max,109031.000000,2019.000000,999977.000000,2.261780e+06,50778.396000

In [4]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
u_company_name_id,824.0,45233.387136,32869.292595,2172.0,14651.00000,34617.0000,77954.00000,109031.000
u_year,824.0,2012.111650,4.166015,2005.0,2009.00000,2012.0000,2016.00000,2019.000
cb_naics,824.0,379140.905340,207892.935774,325.0,324110.00000,336111.0000,523930.00000,999977.000
cb_at,824.0,113685.916945,296348.893884,0.0,763.49200,16471.8695,84863.72725,2261780.000
cb_ni,824.0,2191.241188,5047.784304,-50119.0,-0.31275,484.8620,3470.27075,50778.396

In [5]:
df.columns

Index(['u_company_name_id', 'u_year', 'u_company_name', 'cb_naics', 'u_iso3',
       'u_fye', 'cb_cusip', 'cb_at', 'cb_ni', 'cb_financial_industry'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 824 entries, 0 to 823
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   u_company_name_id      824 non-null    int64
 1   u_year                 824 non-null    int64
 2   u_company_name         824 non-null    object
 3   cb_naics               824 non-null    int64
 4   u_iso3                 824 non-null    object
 5   u_fye                  824 non-null    object
 6   cb_cusip               824 non-null    object
 7   cb_at                  824 non-null    float64
 8   cb_ni                  824 non-null    float64
 9   cb_financial_industry  824 non-null    bool
dtypes: bool(1), float64(2), int64(3), object(4)
memory usage: 58.9+ KB

# Select DataFrame columns

## as attribute

In [7]:
# access an index directly as an attribute
# https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#attribute-access
df.u_company_name

0      British American Tobacco PLC
1      British American Tobacco PLC
2      British American Tobacco PLC
3      British American Tobacco PLC
4      British American Tobacco PLC
                   ...
819             Midatech Pharma PLC
820             Midatech Pharma PLC
821                   Motif Bio plc
822                   Motif Bio plc
823                   Motif Bio plc
Name: u_company_name, Length: 824, dtype: object

In [8]:
# The result is a Pandas-Series
type(df.u_company_name)

pandas.core.series.Series

## using `[]`

When passing a string or a list of strings to `[]`, a subset of columns is selected from the DataFrame.

In [9]:
# select a Series (single column) of a DataFrame
df["u_company_name"]

0      British American Tobacco PLC
1      British American Tobacco PLC
2      British American Tobacco PLC
3      British American Tobacco PLC
4      British American Tobacco PLC
                   ...
819             Midatech Pharma PLC
820             Midatech Pharma PLC
821                   Motif Bio plc
822                   Motif Bio plc
823                   Motif Bio plc
Name: u_company_name, Length: 824, dtype: object

In [10]:
# Note that the result is a Pandas-Series, not a DataFrame!
type(df["u_company_name"])

pandas.core.series.Series

In [11]:
# Multiple columns are selected by supplying a list:
df[["u_company_name", "u_year"]]

                   u_company_name  u_year
0    British American Tobacco PLC    2005
1    British American Tobacco PLC    2006
2    British American Tobacco PLC    2007
3    British American Tobacco PLC    2008
4    British American Tobacco PLC    2009
..                            ...     ...
819           Midatech Pharma PLC    2017
820           Midatech Pharma PLC    2018
821                 Motif Bio plc    2016
822                 Motif Bio plc    2017
823                 Motif Bio plc    2018

[824 rows x 2 columns]

In [12]:
# The result is a DataFrame!
type(df[["u_company_name", "u_year"]])

pandas.core.frame.DataFrame

In [13]:
df.columns

Index(['u_company_name_id', 'u_year', 'u_company_name', 'cb_naics', 'u_iso3',
       'u_fye', 'cb_cusip', 'cb_at', 'cb_ni', 'cb_financial_industry'],
      dtype='object')

In [14]:
# lists created by code are especially useful for column selection

# Example: selecting columns starting with "cb_"
selected_cols = []
for c in df.columns:
    if c.startswith("cb_"):
        selected_cols.append(c)
print(f"selected_cols: {selected_cols}")

df[selected_cols]

selected_cols: ['cb_naics', 'cb_cusip', 'cb_at', 'cb_ni', 'cb_financial_industry']

     cb_naics   cb_cusip      cb_at     cb_ni  cb_financial_industry
0      312230  110448107  32737.984  2707.110                  False
1      312230  110448107  34816.074  3713.506                  False
2      312230  110448107  37161.970  4226.559                  False
3      312230  110448107  40276.807  3591.888                  False
4      312230  110448107  43026.854  4386.107                  False
..        ...        ...        ...       ...                    ...
819    325414  59564R302     66.595   -21.733                  False
820    325414  59564R302     26.056   -19.156                  False
821    325414  619784101     28.426   -40.324                  False
822    325414  619784101     29.188   -44.810                  False
823    325414  619784101     18.724   -13.985                  False

[824 rows x 5 columns]

In [15]:
# Alternative solutions for generating the same `selected_cols`

# List comprehension:
selected_cols = [c for c in df.columns if c.startswith("cb_")]
print(f"From list comprehension: {selected_cols}")

# Using methods included in pandas:
selected_cols = df.columns[df.columns.str.startswith("cb_")]
print(f"Using pandas methods: {selected_cols}")

From list comprehension: ['cb_naics', 'cb_cusip', 'cb_at', 'cb_ni', 'cb_financial_industry']
Using pandas methods: Index(['cb_naics', 'cb_cusip', 'cb_at', 'cb_ni', 'cb_financial_industry'], dtype='object')

## Selecting specific types of columns

The `select_dtypes()` method of `pd.DataFrame` allows you to subset the DataFrame by selecting only specific types of columns.

In [16]:
df.select_dtypes(["int", "float"])

     u_company_name_id  u_year  cb_naics      cb_at     cb_ni
0                14651    2005    312230  32737.984  2707.110
1                14651    2006    312230  34816.074  3713.506
2                14651    2007    312230  37161.970  4226.559
3                14651    2008    312230  40276.807  3591.888
4                14651    2009    312230  43026.854  4386.107
..                 ...     ...       ...        ...       ...
819              62880    2017    325414     66.595   -21.733
820              62880    2018    325414     26.056   -19.156
821              64528    2016    325414     28.426   -40.324
822              64528    2017    325414     29.188   -44.810
823              64528    2018    325414     18.724   -13.985

[824 rows x 5 columns]

In [17]:
# you can also produce a list of the columns:
numeric_columns = df.select_dtypes(["int", "float"]).columns.to_list()
numeric_columns

['u_company_name_id', 'u_year', 'cb_naics', 'cb_at', 'cb_ni']

# Slice DataFrame rows using `[]`

When passing an integer range, or a list/array of integer or booleans to `[]`, the respective rows are selected.

[https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#slicing-ranges](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#slicing-ranges)

In [18]:
# slice rows (exclusive end)
df[0:1]

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.11,False

In [19]:
# Please note that the following will not work because pandas will look for a column with 0 as label when receiving only one integer:
# df[0]

In [20]:
# select the first 10 rows
df[:10]

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False
3,14651,2008,British American Tobacco PLC,312230,GBR,2008-12-31,110448107,40276.807,3591.888,False
4,14651,2009,British American Tobacco PLC,312230,GBR,2009-12-31,110448107,43026.854,4386.107,False
5,14651,2010,British American Tobacco PLC,312230,GBR,2010-12-31,110448107,42882.112,4431.357,False
6,14651,2011,British American Tobacco PLC,312230,GBR,2011-12-31,110448107,42134.790,4808.702,False
7,14651,2012,British American Tobacco PLC,312230,GBR,2012-12-31,110448107,44439.167,6246.234,False
8,14651,2013,British American Tobacco PLC,312230,GBR,2013-12-31,110448107,44552.569,6470.490,False
9,14651,2014,British American Tobacco PLC,312230,GBR,2014-12-31,110448107,40762.953,4852.547,False

In [21]:
# select the last 10 rows
df[-10:]

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry
814,24931,2016,DBV Technologies S.A.,325414,FRA,2016-12-31,23306J101,303.370,-120.853,False
815,24931,2017,DBV Technologies S.A.,325414,FRA,2017-12-31,23306J101,213.760,-177.557,False
816,24931,2018,DBV Technologies S.A.,325414,FRA,2018-12-31,23306J101,196.635,-190.140,False
817,62880,2015,Midatech Pharma PLC,325414,GBR,2015-12-31,59564R302,94.435,-14.892,False
818,62880,2016,Midatech Pharma PLC,325414,GBR,2016-12-31,59564R302,69.937,-24.874,False
819,62880,2017,Midatech Pharma PLC,325414,GBR,2017-12-31,59564R302,66.595,-21.733,False
820,62880,2018,Midatech Pharma PLC,325414,GBR,2018-12-31,59564R302,26.056,-19.156,False
821,64528,2016,Motif Bio plc,325414,GBR,2016-12-31,619784101,28.426,-40.324,False
822,64528,2017,Motif Bio plc,325414,GBR,2017-12-31,619784101,29.188,-44.810,False
823,64528,2018,Motif Bio plc,325414,GBR,2018-12-31,619784101,18.724,-13.985,False

Please not that the integers provided to `[]` refer to **row numbers, not indices**! (this is different from using `.loc[]` and more like using `.iloc[]`)

Passing **booleans** will also select rows (not columns) when used with `[]`

In [22]:
# note that the number of booleans passed to `[]` must equal the number of rows!
# df[[True, False, True]] => ValueError: Item wrong length 3 instead of 824.

In [23]:
# Therefore, booleans used with `[]` are typically generated by code, e.g.:
mask = df["u_year"] == 2005
df[mask].head()

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False
15,13722,2005,Bob Evans Farms Inc.,311612,USA,2006-04-30,096761101,1209.183,54.774,False
27,10161,2005,BP PLC,324110,GBR,2005-12-31,055622104,206914.000,22341.000,False
42,10231,2005,BT Group PLC,517311,GBR,2006-03-31,05577E101,42960.710,2690.697,False
56,39131,2005,Glaxosmithkline PLC,325412,GBR,2005-12-31,37733W105,46747.922,8059.453,False

In [24]:
# You can also use more complex boolean expressions to select rows that fulfill certain conditions
df[(df["u_year"] == 2005) & (df["u_iso3"] == "DEU")].head()

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry
101,4304,2005,Allianz SE,524126,DEU,2005-12-31,018820100,1181690.680,5186.796,True
130,9724,2005,BASF SE,325,DEU,2005-12-31,055262505,42240.532,3560.534,False
144,25503,2005,Daimler AG,336111,DEU,2005-12-31,D1668R123,238772.614,3376.154,False
169,87672,2005,Siemens AG,999977,DEU,2005-09-30,826197501,103945.989,2710.638,False
347,11568,2005,Bayer AG,325,DEU,2005-12-31,072730302,43486.192,1891.167,False

Selecting subsets with []

if you enter str or list[str] => subset of columns

if you enter int:int or list[bool] => subset of rows

In [25]:
df["u_year"]

0      2005
1      2006
2      2007
3      2008
4      2009
       ...
819    2017
820    2018
821    2016
822    2017
823    2018
Name: u_year, Length: 824, dtype: int64

In [26]:
df[["u_year", "u_company_name"]]

     u_year                u_company_name
0      2005  British American Tobacco PLC
1      2006  British American Tobacco PLC
2      2007  British American Tobacco PLC
3      2008  British American Tobacco PLC
4      2009  British American Tobacco PLC
..      ...                           ...
819    2017           Midatech Pharma PLC
820    2018           Midatech Pharma PLC
821    2016                 Motif Bio plc
822    2017                 Motif Bio plc
823    2018                 Motif Bio plc

[824 rows x 2 columns]

In [27]:
df[selected_cols]

     cb_naics   cb_cusip      cb_at     cb_ni  cb_financial_industry
0      312230  110448107  32737.984  2707.110                  False
1      312230  110448107  34816.074  3713.506                  False
2      312230  110448107  37161.970  4226.559                  False
3      312230  110448107  40276.807  3591.888                  False
4      312230  110448107  43026.854  4386.107                  False
..        ...        ...        ...       ...                    ...
819    325414  59564R302     66.595   -21.733                  False
820    325414  59564R302     26.056   -19.156                  False
821    325414  619784101     28.426   -40.324                  False
822    325414  619784101     29.188   -44.810                  False
823    325414  619784101     18.724   -13.985                  False

[824 rows x 5 columns]

In [28]:
df[2:5]

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False
3,14651,2008,British American Tobacco PLC,312230,GBR,2008-12-31,110448107,40276.807,3591.888,False
4,14651,2009,British American Tobacco PLC,312230,GBR,2009-12-31,110448107,43026.854,4386.107,False

In [29]:
df[df["u_year"] == 2005].head()

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False
15,13722,2005,Bob Evans Farms Inc.,311612,USA,2006-04-30,096761101,1209.183,54.774,False
27,10161,2005,BP PLC,324110,GBR,2005-12-31,055622104,206914.000,22341.000,False
42,10231,2005,BT Group PLC,517311,GBR,2006-03-31,05577E101,42960.710,2690.697,False
56,39131,2005,Glaxosmithkline PLC,325412,GBR,2005-12-31,37733W105,46747.922,8059.453,False

# Select rows and columns using the `df.loc[]` method

`.loc[]` selects rows by their indices and and columns by their label. Alternatively, booleans are accepted.

## Select rows using ```loc```

### Using indices

In [30]:
df.loc[[0, 15, 27]]

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False
15,13722,2005,Bob Evans Farms Inc.,311612,USA,2006-04-30,096761101,1209.183,54.774,False
27,10161,2005,BP PLC,324110,GBR,2005-12-31,055622104,206914.000,22341.000,False

### Using Booleans

In [31]:
df.loc[df["u_year"] == 2005].head()

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False
15,13722,2005,Bob Evans Farms Inc.,311612,USA,2006-04-30,096761101,1209.183,54.774,False
27,10161,2005,BP PLC,324110,GBR,2005-12-31,055622104,206914.000,22341.000,False
42,10231,2005,BT Group PLC,517311,GBR,2006-03-31,05577E101,42960.710,2690.697,False
56,39131,2005,Glaxosmithkline PLC,325412,GBR,2005-12-31,37733W105,46747.922,8059.453,False

## Select columns using ```loc```

In [32]:
df.loc[:, ["u_year", "u_company_name"]]

     u_year                u_company_name
0      2005  British American Tobacco PLC
1      2006  British American Tobacco PLC
2      2007  British American Tobacco PLC
3      2008  British American Tobacco PLC
4      2009  British American Tobacco PLC
..      ...                           ...
819    2017           Midatech Pharma PLC
820    2018           Midatech Pharma PLC
821    2016                 Motif Bio plc
822    2017                 Motif Bio plc
823    2018                 Motif Bio plc

[824 rows x 2 columns]

## Select rows and columns using `loc`

In [33]:
df.loc[df["u_year"] > 2007, ["u_company_name", "u_year"]]

                   u_company_name  u_year
3    British American Tobacco PLC    2008
4    British American Tobacco PLC    2009
5    British American Tobacco PLC    2010
6    British American Tobacco PLC    2011
7    British American Tobacco PLC    2012
..                            ...     ...
819           Midatech Pharma PLC    2017
820           Midatech Pharma PLC    2018
821                 Motif Bio plc    2016
822                 Motif Bio plc    2017
823                 Motif Bio plc    2018

[673 rows x 2 columns]

# Exercise

*Preparations*
* create new jupyter notebook
* store it under notebooks/own_exercises

*Tasks*
1. Load the first sheet of the Excel file "wdi_reduced.xlsx" into a pandas DataFrame (see [here](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html) for help with `pandas.read_excel()`). *Hint*: you need to save the notebook in a suitable directory before you can use relative file paths! Also, if you use a different folder from the one specified in *preparations*, you may have to adjust the relative path, e.g. the number of times you use the "../" prefix.
2. What are the data types of the columns?
3. Display the descriptive statistics of the numeric columns.
4. Select the columns *countryname* and *year* from the DataFrame.
5. Select the rows from Germany and France.
6. Bonus: Select the rows from Germany and France in the years 2008 to 2010 and all columns starting with 'country' as well as *year*.
7. Bonus: Select only numeric columns.
8. Bonus: Select the numeric columns except those starting with "NY_".