# Modifying DataFrames - Intro

This chapter covers various methods to modify `pandas.DataFrame`s.

# Preparations

In [1]:
import pandas as pd

pd.set_option("display.max_columns", 500)
df = pd.read_csv("../../data/raw/financial_data_intro.csv")
df.head(3)

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False

# Inserting Columns

In [2]:
# insert column with a scalar value - the value will be propagated for filling the entire column
df["new column"] = "something new"
df.head(3)

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,new column
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,something new
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,something new
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False,something new

In [3]:
# insert a boolean column
df["is_after_2007"] = df["u_year"] > 2007
df.head(3)

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,new column,is_after_2007
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,something new,False
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,something new,False
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False,something new,False

In [4]:
# Calculations with several columns (note that you can either use the `[]` or the `.` on the right side of the `=`)
df["roa"] = df["cb_ni"] / df["cb_at"]
df.head(3)

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,new column,is_after_2007,roa
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,something new,False,0.082690
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,something new,False,0.106661
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False,something new,False,0.113733

# Modify values with `loc`

`loc` can not only be used for "reading" a subset of rows and/or columns from a DataFrame but can also be used to change the values of such a subset.

[https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html)

In [5]:
# Replace all values of u_year with 9999 firm-years from 2005:
df.loc[df["u_year"] == 2005, "u_year"] = 9999
df.head(3)

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,new column,is_after_2007,roa
0,14651,9999,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,something new,False,0.082690
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,something new,False,0.106661
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False,something new,False,0.113733

In [6]:
# Take a look at some of the changed rows
df[df["u_year"] == 9999].head(3)

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,new column,is_after_2007,roa
0,14651,9999,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,something new,False,0.082690
15,13722,9999,Bob Evans Farms Inc.,311612,USA,2006-04-30,096761101,1209.183,54.774,False,something new,False,0.045298
27,10161,9999,BP PLC,324110,GBR,2005-12-31,055622104,206914.000,22341.000,False,something new,False,0.107972

In [7]:
# Check: there should no longer be entries with years == 2005
df.loc[df["u_year"] == 2005]

Empty DataFrame
Columns: [u_company_name_id, u_year, u_company_name, cb_naics, u_iso3, u_fye, cb_cusip, cb_at, cb_ni, cb_financial_industry, new column, is_after_2007, roa]
Index: []

In [8]:
# Undo the damage:
df.loc[df["u_year"] == 9999, "u_year"] = 2005
df.head(3)

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,new column,is_after_2007,roa
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,something new,False,0.082690
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,something new,False,0.106661
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False,something new,False,0.113733

# Deleting columns

`DataFrame.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')`

Deletes columns by label or rows by index label. Note that, by default, rows are dropped (axis=0)! For dropping columns you need to either specify `axis=1` or the `columns=...` argument instead of the `labels=...` argument (see below).

Furthermore, `.drop()` returns a changed copy of the DataFrame. Specify `inplace=True` when the original DataFrame is to be modified.

[https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html)

In [9]:
# use columns=[] so that pandas looks for columns to be removed and not for a row with index "roa"!
df.drop(columns=["roa"]).head(3)

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,new column,is_after_2007
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,something new,False
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,something new,False
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False,something new,False

In [10]:
# Lists of labels can also be provided, and we overwrite the dataframe with a reduced copy
df = df.drop(columns=["new column", "is_after_2007"])
df.head(3)

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,roa
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,0.082690
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,0.106661
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False,0.113733

# Exercise 1

1. Load the file 'financial_data_intro.csv' into a `pd.DataFrame`.
2. Replace *u_iso3* with "UK" for all rows that have *u_iso3* == "GBR".
3. Convert *cb_naics* to data type `str`.
4. Create a new column *industry_label* that takes the value "special" if *cb_naics* starts with "6", and "normal" otherwise.
5. Replace *cb_ni* with `pd.NA` if *u_year* == 2005.
6. Calculate a new column taking the value 1 if *cb_ni* is negative and 0 if *cb_ni* is >= 0.
7. Bonus: Create a new column *industry_label_2* that takes the value True if *cb_naics* starts with "6", and False otherwise.
8. Bonus: delete all numeric columns in-place.
9. Bonus: convert the column *u_fye* to a `datetime` data type

# The `replace` method

`DataFrame.replace(to_replace=None, value=None, inplace=False, limit=None, regex=False, method='pad')`

Replace values in `to_replace` with `value`.

Values of the DataFrame are replaced with other values dynamically. This differs from updating with ```.loc``` or ```.iloc```, which require you to specify a location to update with some value.

* `to_replace`: str, regex, list, dict, Series, int, float, or None
* `value`: scalar, dict, list, str, regex, default None

The `replace` returns a changed copy of the DataFrame object and leaves the original unchanged, unless `inplace=True` is specified.

[https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html)

In [11]:
# Replace a certain single value with another (across all columns!)
df.replace(to_replace=14651, value=99999)

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,roa
0,99999,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,0.082690
1,99999,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,0.106661
2,99999,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False,0.113733
3,99999,2008,British American Tobacco PLC,312230,GBR,2008-12-31,110448107,40276.807,3591.888,False,0.089180
4,99999,2009,British American Tobacco PLC,312230,GBR,2009-12-31,110448107,43026.854,4386.107,False,0.101939
...,...,...,...,...,...,...,...,...,...,...,...
819,62880,2017,Midatech Pharma PLC,325414,GBR,2017-12-31,59564R302,66.595,-21.733,False,-0.326346
820,62880,2018,Midatech Pharma PLC,325414,GBR,2018-12-31,59564R302,26.056,-19.156,False,-0.735186
821,64528,2016,Motif Bio plc,325414,GBR,2016-12-31,619784101,28.426,-40.324,False,-1.418560
822,64528,2017,Motif Bio plc,325414,GBR,2017-12-31,619784101,29.188,-44.810,False,-1.535220
823,64528,2018,Motif Bio plc,325414,GBR,2018-12-31,619784101,18.724,-13.985,False,-0.746902

In [12]:
# The original has not changed!
df

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,roa
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,0.082690
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,0.106661
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False,0.113733
3,14651,2008,British American Tobacco PLC,312230,GBR,2008-12-31,110448107,40276.807,3591.888,False,0.089180
4,14651,2009,British American Tobacco PLC,312230,GBR,2009-12-31,110448107,43026.854,4386.107,False,0.101939
...,...,...,...,...,...,...,...,...,...,...,...
819,62880,2017,Midatech Pharma PLC,325414,GBR,2017-12-31,59564R302,66.595,-21.733,False,-0.326346
820,62880,2018,Midatech Pharma PLC,325414,GBR,2018-12-31,59564R302,26.056,-19.156,False,-0.735186
821,64528,2016,Motif Bio plc,325414,GBR,2016-12-31,619784101,28.426,-40.324,False,-1.418560
822,64528,2017,Motif Bio plc,325414,GBR,2017-12-31,619784101,29.188,-44.810,False,-1.535220
823,64528,2018,Motif Bio plc,325414,GBR,2018-12-31,619784101,18.724,-13.985,False,-0.746902

In [13]:
# this will overwrite df with a modified copy (alternatively, you could have used inplace=True, here)
df = df.replace(to_replace=14651, value=99999)
df

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,roa
0,99999,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,0.082690
1,99999,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,0.106661
2,99999,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False,0.113733
3,99999,2008,British American Tobacco PLC,312230,GBR,2008-12-31,110448107,40276.807,3591.888,False,0.089180
4,99999,2009,British American Tobacco PLC,312230,GBR,2009-12-31,110448107,43026.854,4386.107,False,0.101939
...,...,...,...,...,...,...,...,...,...,...,...
819,62880,2017,Midatech Pharma PLC,325414,GBR,2017-12-31,59564R302,66.595,-21.733,False,-0.326346
820,62880,2018,Midatech Pharma PLC,325414,GBR,2018-12-31,59564R302,26.056,-19.156,False,-0.735186
821,64528,2016,Motif Bio plc,325414,GBR,2016-12-31,619784101,28.426,-40.324,False,-1.418560
822,64528,2017,Motif Bio plc,325414,GBR,2017-12-31,619784101,29.188,-44.810,False,-1.535220
823,64528,2018,Motif Bio plc,325414,GBR,2018-12-31,619784101,18.724,-13.985,False,-0.746902

In [14]:
# Passing a dictionary as `to_replace` specifies different original values to look for in the respective columns
df = df.replace(to_replace={"u_company_name_id": 99999, "u_iso3": "GBR"}, value=88888)
df

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,roa
0,88888,2005,British American Tobacco PLC,312230,88888,2005-12-31,110448107,32737.984,2707.110,False,0.082690
1,88888,2006,British American Tobacco PLC,312230,88888,2006-12-31,110448107,34816.074,3713.506,False,0.106661
2,88888,2007,British American Tobacco PLC,312230,88888,2007-12-31,110448107,37161.970,4226.559,False,0.113733
3,88888,2008,British American Tobacco PLC,312230,88888,2008-12-31,110448107,40276.807,3591.888,False,0.089180
4,88888,2009,British American Tobacco PLC,312230,88888,2009-12-31,110448107,43026.854,4386.107,False,0.101939
...,...,...,...,...,...,...,...,...,...,...,...
819,62880,2017,Midatech Pharma PLC,325414,88888,2017-12-31,59564R302,66.595,-21.733,False,-0.326346
820,62880,2018,Midatech Pharma PLC,325414,88888,2018-12-31,59564R302,26.056,-19.156,False,-0.735186
821,64528,2016,Motif Bio plc,325414,88888,2016-12-31,619784101,28.426,-40.324,False,-1.418560
822,64528,2017,Motif Bio plc,325414,88888,2017-12-31,619784101,29.188,-44.810,False,-1.535220
823,64528,2018,Motif Bio plc,325414,88888,2018-12-31,619784101,18.724,-13.985,False,-0.746902

In [15]:
# Passing a dictionary as `value` specifies different replacement values to use in the respective columns
df = df.replace(to_replace=88888, value={"u_company_name_id": 14651, "u_iso3": "GBR"})
df

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,roa
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,0.082690
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,0.106661
2,14651,2007,British American Tobacco PLC,312230,GBR,2007-12-31,110448107,37161.970,4226.559,False,0.113733
3,14651,2008,British American Tobacco PLC,312230,GBR,2008-12-31,110448107,40276.807,3591.888,False,0.089180
4,14651,2009,British American Tobacco PLC,312230,GBR,2009-12-31,110448107,43026.854,4386.107,False,0.101939
...,...,...,...,...,...,...,...,...,...,...,...
819,62880,2017,Midatech Pharma PLC,325414,GBR,2017-12-31,59564R302,66.595,-21.733,False,-0.326346
820,62880,2018,Midatech Pharma PLC,325414,GBR,2018-12-31,59564R302,26.056,-19.156,False,-0.735186
821,64528,2016,Motif Bio plc,325414,GBR,2016-12-31,619784101,28.426,-40.324,False,-1.418560
822,64528,2017,Motif Bio plc,325414,GBR,2017-12-31,619784101,29.188,-44.810,False,-1.535220
823,64528,2018,Motif Bio plc,325414,GBR,2018-12-31,619784101,18.724,-13.985,False,-0.746902

# Rename columns

see [https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html#pandas.DataFrame.rename)

In [16]:
# Renaming some of the columns
df.rename(columns={"u_year": "the year", "u_company_name": "the Name of the Company"}).head(2)

,u_company_name_id,the year,the Name of the Company,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,roa
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,0.082690
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,0.106661

In [17]:
# the original df is not changed
df.head(2)

,u_company_name_id,u_year,u_company_name,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,roa
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,0.082690
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,0.106661

In [18]:
# now overwrite the df
df = df.rename(columns={"u_year": "the year", "u_company_name": "the Name of the Company"})
df.head(2)

,u_company_name_id,the year,the Name of the Company,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,roa
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,0.082690
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,0.106661

In [19]:
# There are also functions to add prefixes or suffixes to the column names - these cannot make changes in-place!
df = df.add_prefix("my_prefix_")
df.head(2)

,my_prefix_u_company_name_id,my_prefix_the year,my_prefix_the Name of the Company,my_prefix_cb_naics,my_prefix_u_iso3,my_prefix_u_fye,my_prefix_cb_cusip,my_prefix_cb_at,my_prefix_cb_ni,my_prefix_cb_financial_industry,my_prefix_roa
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,0.082690
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,0.106661

In [20]:
# Remove the prefix, e.g. by directly changing the df.columns property!
df.columns = df.columns.str.replace("my_prefix_", "")
df.head(2)

,u_company_name_id,the year,the Name of the Company,cb_naics,u_iso3,u_fye,cb_cusip,cb_at,cb_ni,cb_financial_industry,roa
0,14651,2005,British American Tobacco PLC,312230,GBR,2005-12-31,110448107,32737.984,2707.110,False,0.082690
1,14651,2006,British American Tobacco PLC,312230,GBR,2006-12-31,110448107,34816.074,3713.506,False,0.106661

# Exercise 2

1. Load the file 'bank-additional-full.csv' into a `pd.DataFrame`.
2. Rename the column 'y' to 'target'.
3. Drop the column 'duration'.
4. Give all columns, other than 'y', the prefix 'feature_'.
5. Replace the value 999 in column 'feature_pdays' with `pd.NA`.